# Generated by Django 4.2.4 on 2023-08-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
