# Generated by Django 4.2.4 on 2023-08-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_activity_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("active", models.BooleanField(default=False)),
                ("logo", models.ImageField(upload_to="technology")),
            ],
        ),
    ]
