# Generated by Django 4.2.4 on 2023-08-18 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_technology"),
    ]

    operations = [
        migrations.AddField(
            model_name="technology",
            name="experience",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
            ),
        ),
    ]
