# Generated by Django 4.2.4 on 2023-08-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_technology_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="technology",
            name="type",
            field=models.CharField(
                choices=[
                    ("BACKEND", "Backend"),
                    ("FRONTEND", "Frontend"),
                    ("MOBILE", "Mobile"),
                    ("DEVOPS", "DevOps"),
                    ("DATABASE", "Database"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
    ]
