# Generated by Django 4.2.4 on 2023-08-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_technology_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="technology",
            name="link",
            field=models.URLField(blank=True),
        ),
    ]
