# Generated by Django 4.2.4 on 2023-08-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_workcompany_alter_technology_options_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="projects", to="core.workcompany"
            ),
        ),
    ]
