# Generated by Django 4.2.4 on 2023-12-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_project_options_project_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="customercompany",
            name="put_white_background",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="put_white_background",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workcompany",
            name="put_white_background",
            field=models.BooleanField(default=False),
        ),
    ]
