# Generated by Django 4.2.4 on 2023-12-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_customercompany_put_white_background_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="demo_address",
            field=models.CharField(blank=True),
        ),
    ]
