# Generated by Django 4.2.4 on 2023-12-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_project_demo_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technology",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
