# Generated by Django 4.2.4 on 2023-12-30 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_customercompany_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField()),
                ("link", models.URLField(blank=True)),
                ("logo", models.ImageField(upload_to="event")),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("thumbnail", models.ImageField(upload_to="lecture")),
                ("link", models.URLField(blank=True)),
                ("date", models.DateField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lectures", to="core.event"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lecture",
                "verbose_name_plural": "Lectures",
                "ordering": ["-date"],
            },
        ),
    ]
