# Generated by Django 4.2.4 on 2023-12-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_event_lecture"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="duration",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
