# Generated by Django 4.2.4 on 2024-02-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_lecture_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="work_project_logos"),
        ),
        migrations.AlterField(
            model_name="project",
            name="screenshot",
            field=models.ImageField(blank=True, null=True, upload_to="work_project_screenshots"),
        ),
    ]
